### ISSUE TITLE
Client Feedback re: Text Task

### ISSUE THREAD

**Issue by michaelfitzhavey** [holistic-web/website-gmc#41]
It seems we've had some negative feedback re: our text task. Let's resolve any errors we left in there...

```
Also there are a few small things that don't seem to be updated yet. 
1. The text on the homepage over Ifrah with the camera should just say "We are the Global Media Campaign to end FGM". 
2. Lucy Ann's quote is missed "need" in "we don't need minders"
3. Can we put Lucy Ann's title under jar name in same colour font: "Head of Broadcasting, Sierra Leone Broadcasting Company". 

Thank you!!
```

# Tasks
- [x] figure out what wasn't done right and add each of those as extra tasks here
- [x] complete all fixes and list what was changed
- [ ] add any changes that weren't errors in your last task (#36) to a new issue as new improvements

**Comment by michaelfitzhavey** [comment]
@andrewlew1s  is this solved? please update and manage issues

**Comment by andrewlew1s** [comment]
Text Changes: 

Descriptions of Lucy Anne's title and quote as requested above by Andrew.

Further changes by Mike as per client request
